
export const FETCHED_FAVORITE_TRACKS = 'FETCHED_FAVORITE_TRACKS';
export const REQUESTED_FAVORITE_TRACKS = 'REQUESTED_FAVORITE_TRACKS';
export const REQUESTED_FAVORITE_TRACKS_SUCCEED = 'REQUESTED_FAVORITE_TRACKS_SUCCEED';
export const REQUESTED_FAVORITE_TRACKS_FAILED = 'REQUESTED_FAVORITE_TRACKS_FAILED';

export const SET_PLAYER = 'SET_PLAYER';
export const FETCHED_TRACK = 'FETCHED_TRACK';
export const PLAY_TRACK = 'PLAY_TRACK';
export const PAUSE_TRACK = 'PAUSE_TRACK';
export const SET_PLAYER_INTERVAL = 'SET_PLAYER_INTERVAL';
export const SET_CURRENT_TIME = 'SET_CURRENT_TIME';
export const SEEK_TO = 'SEEK_TO';

export const FETCHED_NEXT = 'FETCHED_NEXT';
export const FETCHED_PREVIOUS = 'FETCHED_PREVIOUS';