
export const FETCHED_FAVORITE_TRACKS = 'FETCHED_FAVORITE_TRACKS';
export const REQUESTED_FAVORITE_TRACKS = 'REQUESTED_FAVORITE_TRACKS';
export const REQUESTED_FAVORITE_TRACKS_SUCCEED = 'REQUESTED_FAVORITE_TRACKS_SUCCEED';
export const REQUESTED_FAVORITE_TRACKS_FAILED = 'REQUESTED_FAVORITE_TRACKS_FAILED';
