
export const FETCHED_USER = 'FETCHED_USER';
export const REQUESTED_USER = 'REQUESTED_USER';
export const REQUESTED_USER_SUCCEED = 'REQUESTED_USER_SUCCEED';
export const REQUESTED_USER_FAILED = 'REQUESTED_USER_FAILED';