
export const FETCHED_SEARCH_TRACKS = 'FETCHED_SEARCH_TRACKS';
export const REQUESTED_SEARCH_TRACKS = 'REQUESTED_SEARCH_TRACKS';
export const REQUESTED_SEARCH_TRACKS_SUCCEED = 'REQUESTED_SEARCH_TRACKS_SUCCEED';
export const REQUESTED_SEARCH_TRACKS_FAILED = 'REQUESTED_SEARCH_TRACKS_FAILED';