
export const FETCHED_SEARCH_TRACKS = 'FETCHED_SEARCH_TRACKS';
export const FETCHED_SEARCH_TRACKS_BY_PAGE = 'FETCHED_SEARCH_TRACKS_BY_PAGE';
export const REQUESTED_SEARCH_TRACKS = 'REQUESTED_SEARCH_TRACKS';
export const REQUESTED_SEARCH_TRACKS_SUCCEED = 'REQUESTED_SEARCH_TRACKS_SUCCEED';
export const REQUESTED_SEARCH_TRACKS_FAILED = 'REQUESTED_SEARCH_TRACKS_FAILED';
export const RESET_SEARCH_TRACKS = 'RESET_SEARCH_TRACKS';