
export const FETCHED_SEARCH_TRACKS = 'FETCHED_SEARCH_TRACKS';
export const FETCHED_SEARCH_TRACKS_BY_PAGE = 'FETCHED_SEARCH_TRACKS_BY_PAGE';
export const REQUESTED_SEARCH_TRACKS = 'REQUESTED_SEARCH_TRACKS';
export const REQUESTED_SEARCH_TRACKS_SUCCEED = 'REQUESTED_SEARCH_TRACKS_SUCCEED';
export const REQUESTED_SEARCH_TRACKS_FAILED = 'REQUESTED_SEARCH_TRACKS_FAILED';
export const RESET_SERACH_TRACKS = 'RESET_SERACH_TRACKS';

export const FETCHED_WAVEFORM_TRACKS = 'FETCHED_WAVEFORM_TRACKS';
export const REQUESTED_WAVEFORM_SUCCEED = 'REQUESTED_WAVEFORM_SUCCEED';